shared:
  activities:
    - Acrobatics
    - Acting
    - Animation
    - Visiting the aquarium
    - Archery
    - Astronomy
    - Baking
    - Beekeeping
    - Birdwatching
    - Playing a board game
    - Watering your plants
    - Bowling
    - Boxing
    - Calligraphy
    - Camping
    - Canoeing
    - Chalk art
    - Cheesemaking
    - Chess
    - Stand up comedy
    - Reading a comic book
    - Eating a snack
    - Cooking
    - Cosplay
    - Crafting
    - Creative writing
    - Cycling
    - Dance
    - Darts
    - Design
    - Digital art
    - Drawing
    - Electronics
    - Embroidery
    - Cleaning up 10 pieces of rubbish
    - Putting together a fashionable outfit
    - Filmmaking
    - Fishing
    - Working out
    - Playing a video game
    - Gardening
    - Hiking
    - Home improvement project
    - Riding a horse
    - Skating
    - Journaling
    - Juggling
    - Karaoke
    - Kayaking
    - Flying a kite
    - Knitting
    - Learning a language
    - Magic
    - Makeup
    - Martial arts
    - Media production
    - Metal detecting
    - Metalworking
    - Model building
    - Motor sports
    - Mountain biking
    - Listening to music
    - Making music
    - Nail art
    - Origami
    - Paintball
    - Painting
    - Photography
    - Podcasting
    - Playing pool
    - Pottery
    - Puzzles
    - Quilting
    - Reading
    - Remote control vehicles
    - Reuse or repair something
    - Robotics
    - Rock climbing
    - Roller skating
    - Running
    - Sailing
    - Boating
    - Scouting
    - Scrapbooking
    - Scuba diving
    - Sculpting
    - Sewing
    - Singing
    - Skating
    - Skiing
    - Snowboarding
    - Skydiving
    - Street art
    - Surfing
    - Bodyboarding
    - Swimming
    - Tennis
    - Trainspotting
    - Booking a holiday
    - Vegetable gardening
    - Playing a video game
    - Weightlifting
    - Woodworking
    - Playing a word game
    - Yoga
    - Fencing
    - Stone carving
    - Candle making
    - Leather crafting
    - Horse riding
    - Metalworking
    - Archery
    - Herbalism
    - Doll making
    - Sewing
    - Embroidery
    - Painting
    - Drawing
    - Jewellery making
    - Mixology (cocktail making)
    - Blogging
    - Soap making
    - Poetry
    - Story writing
    - Article writing
    - Doing a puzzle
    - Stargazing
    - Programming
    - Hacking
    - Going on a walk
    - Cycling
    - Watching a documentary
    - Making digital art
    - Singing
    - Making digital music
    - Pottery
    - Witchcraft
    - Face painting
    - Cosplaying
    - Surfing
    - Sailing
    - Skiing
    - Snowboarding
    - Running
    - Hiking
    - Dancing
    - Rearranging your furniture
    - Gymnastics
    - Martial arts
    - Bodybuilding
    - Activism
    - Public speaking
    - Debating
    - Team sports
    - Playing a musical instrument
    - Kayaking
    - Canoeing
    - Boxing
    - Kickboxing
    - Travelling
    - Fishing
    - Cooking
    - Baking
    - Yoga
    - Bird watching
    - Gardening
    - Scrapbooking
    - Listening to music
    - Poetry
    - Photography
    - Watching TV
    - Musical theatre
    - Golfing
    - Bowling
    - Bingo
    - Reading
    - Drinking a coffee
    - Learning magic tricks
    - Puppetry
    - Chess
    - Juggling
    - Stand-up comedy
    - Pranking others
    - Nail painting
    - Graffiti
    - Calligraphy
    - Beekeeping
    - Camping
    - Crossword puzzles
    - Parkour
    - Roller skating
    - Vehicle restoration
    - Listening to podcasts
    - Ice skating
    - Volunteering
    - Pole dancing
    - Writing book or film reviews
    - Bullet journalling
    - Picking flowers
    - Going on picnics
    - Sudoku
    - Animation
    - Making playlists
    - Playing roleplay games
    - Modelling
    - Hair styling
    - Getting a tattoo
    - Cake decorating
